# Generated by Django 3.2.18 on 2023-03-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetBanking',
            fields=[
                ('Username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=14)),
                ('Bank', models.CharField(max_length=25)),
                ('Balance', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'CONFIRMED'), ('cancelled', 'CANCELLED')], default='cancelled', max_length=20),
        ),
    ]
